Add master script
moreh-dev/transformers pull request #10
Opened 2023-07-03 09:09 UTC by HDThang

Modify training script in the flowing tasks to run mlflow while training models:
-audio classification
-contrastive-image-text
-image classification
-image pretraining
-language modeling
-multiple choice
-semantic segmentation
-speech recognition
-summarization
-text classification
-token classification
-translation

2023-07-03 09:16 UTC, huonglarne reviewed
I noticed some file with strange names
And some need refactoring

2023-07-03 09:16 UTC, huonglarne commented on examples/pytorch/language-modeling/.nfs00000000864964a600000492
> +#### end list ####
what is this file? did you commit it by mistake?

2023-07-03 09:16 UTC, huonglarne commented on examples/pytorch/text-classification/.nfs00000000865205a400000493
> +bigscience/bloom-560m 16 3
what is this file? did you commit it by mistake?

2023-07-03 09:16 UTC, huonglarne commented on examples/pytorch/contrastive-image-text/run_clip.py
> +        with mlflow_runner:
I think using ML flow like this makes the code a bit hard to read. You dont have to fix it now but maybe in the future, refactor this into a function called log_to_ml_flow or something

2023-07-03 09:39 UTC, yeomni commented on examples/pytorch/audio-classification/run_audio_classification.py
> +    experiment_id = mlflow.create_experiment('translateion-{}'.format(model_args.model_name_or_path))
According to what you've mentioned in your Daily Scrum, if what I think is right, we should be still able to use MLFlow Tracking just using Accelerate instance. Then do we not need to add all these repetitive MLFlow APIs for each task?

2023-07-04 08:12 UTC, loctxmoreh requested changes
There is a couple of issues with the use of `mlflow`:
* Update `env.yml` to include `mlflow` as a dependencies
* Or, consider making `mlflow` optional. If `mlflow` is not installed, the script should still run
* Automatically start mlflow server (if available), before running the train script 
* Using the environment variable `MLFLOW_TRACKING_URI` in bash script instead of this line in Python: `mlflow.set_tracking_uri()`

Also, please remove temp files that are accidentally committed, and be mindful when adding file to commit

2023-07-05 04:34 UTC, thuc-moreh approved these changes

2023-07-10 07:58 UTC, yeomni commented
@HDThang If you have resolved all the commented issues, please merge this PR.

2023-09-27 06:44 UTC, yeomni commented
Closed as deprecated

2023-09-27 06:44 UTC, closed without merging