Add master script
moreh-dev/transformers pull request #9
Opened 2023-06-23 09:54 UTC by HDThang

# What does this PR do?
- Reformat master script
- Allow using args from model_batchsize.txt file
- Allow using memory_record_moreh.sh to log memory
- Allow train all the task
- Add readme.md

2023-06-26 04:34 UTC, huonglarne approved these changes
The master script LGTM.

In the next PR, I suggest you:

- integrate the rest of the tasks into the master script.
- refactor the master script to be easier to read. I do see some repetition between the tasks's code. Try putting them into separate scripts, like a function.

2023-06-26 08:59 UTC, loctxmoreh requested changes

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/text-classification/.nfs0000000087a6133400000490
This temporary file shouldn't be tracked with git. Please be mindful about which files get staged for commit.

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/all_scripts/bart-base-16.memory
I believe this file is added by accident. Please remove

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/all_scripts/bert-base-uncased-64.memory
Also this one is added by accident, too

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/all_scripts/master.sh
> +-t, --target         Run the task you want
This usage block claims the flag is `-t` & `--target`, but later in the `case` block, the argument is matched with `-t | --task`. This is very confusing and looks like a mistake.

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/all_scripts/master.sh
> +                        /bin/chmod a+x ../text-classification/train_glue.sh
This use of `chmod` is completely unnecessary. Git does tracks the mode (read, write, execute bits for users, groups and all users) of each file, so instead of putting `chmod` in a script like this, just `chmod` the script directly and this change will be recorded by git.

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/question-answering/train_qa.sh
> +python train_qa.sh \
This clearly is a typo. Please fix

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/run_task.sh
There is already a `master.sh` script. What is the point of this `run_task.sh` file?

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/multiple-choice/train.sh
This script requires `--use_auth_token` set to `False` (instead of current value `True`) to work.

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/semantic-segmentation/train.sh
Also need `--use_auth_token` set to `False` to work

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/text-classification/train_xnli.sh
`LOG_DIR` and `OUTPUT_DIR` are not initialized

2023-06-26 08:59 UTC, loctxmoreh commented on examples/pytorch/multiple-choice/train.sh
The flag `--use_auth_token` need to be set to `False` for this to work

2023-06-27 10:17 UTC, HDThang commented on examples/pytorch/all_scripts/master.sh
> +-t, --target         Run the task you want
That's a mistake indeed. It will be fixed in the next PR.

2023-06-28 02:25 UTC, thuc-moreh commented on examples/pytorch/README.md
> +    bash train.sh -m google/mobilebert-uncased -b 64 -g 1
Are all the flags (-b 64 -g 1 -m) optional or necessary here? Ideally they should be optional as the users don't have to figure out what values of the flags to run the models.

2023-06-28 04:58 UTC, loctxmoreh approved these changes

2023-06-28 06:15 UTC, merged